apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:UQO0A+YKNhbQcA1ICQoJSW8jpasbrQGCkgj+AsSYCBU17SyqVlBWKl0Cwylc2XZxOxbjEV2+neGnjKy0+/CKXryKivetT89F6VpDJzBlWoN8+T/0SZJgAYfozckv8srh7oAI4BDeN1OulG2cohBrhYYdaX2dSKmppuA=,iv:EuLgr0Iap82oDAkL13l8cxI+fjWZ1gM2MDEzaHdGlrM=,tag:NYk4YG6emGOW1rgBdiY5Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-29T13:52:59Z"
    mac: ENC[AES256_GCM,data:JHP0bkL5ChHvJH4OLm6foFhfxhKm3PJjSKhXFeMhxdpxRqeNRJ4d+IEmT2QrS/axH0KNmh8BGJ3qSlHeYlH3yPLs5Q9inPv4qJBxBEJFVIYc5efZ5iHeaau8n0Z8U54ri89cZoVU71cy04jW+KEkN2X85BJUGLPmrYahc+D6iDE=,iv:Ech5f1BIGLwyS1N69msgQIMYaQbxJ6i+mUjgYCrVu+k=,tag:ZaP6SBwTF2EOMy5cWC16vA==,type:str]
    pgp:
        - created_at: "2022-03-29T13:52:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9h0z2gYaLuTAQ/+IG6FHpfzz+5sbtVjXOxAdE7/G3bAifrdfrMPQKO14mpT
            PkUHZBPfJwQOcda5s+6i8uWofnwiNE4UFFvEDIG2liqu58p/0qToIhulpL/WZ7aE
            5ebiF5iXwTP55m5bQ7k4GFrZWG34mRiCIpWAAWj+rIAoCVK3LkklJuiS2D+cFhRm
            DDrzf0EdCZ5ZXcBJAPCbbjyLJ4H2yCSZbgUoocc6qd5hCHxpYagFs6+p9VP36JSY
            7mm800h91ch532bA3nSceTSI+5Q41bKgt4WfYZjarM55kTk4e/D/RfYELitiwn+a
            0zi0tj48Uq3QLaYCdH/aOYMhC79laCmH7oyjklkxfO2qZQBPrXEnGgE+VcB+Leg5
            NDy7xYvdXlyETJWDY1nz2R1uLmk8MWvr2LBnB1XtXCSKGGrjoC6Kt9k69nz9i2g/
            18gtA6pNBrV91XwEFLRNxDnztp2Sr4IsQHM8pAcKMzcud+IFo6zzEZNDjNOzxyUE
            plI0vC37zPxy31JtnQKCY4YcCrBd6/0t7XqwuvAbc5Qqd6PERAwpTI9Qhu/9CU0t
            YHKA/IDo8pAFzpvwQXOOsVD+k81C9ArE02dwvffa+8IOnjtgaLX6AX5IUsCwPZpl
            oFfWWxLl/wbHfZhAOVaoCaQ1eW7rGi++ZYPlbN6SYjjnLrsuzwqPDakVyYh5wI3S
            XgEGDv4BCkBTLnjZnCRXNR0xkk9CE+7rJ5fuaWkc+LZd05mVMora78DCiYpUL6TB
            y/wOVP0QGoBBbBO/AmK4jTVk/H1B6BpVjOne9E3Dh9O7yZY6wM2rQIaMMS0hKCc=
            =aa0S
            -----END PGP MESSAGE-----
          fp: 4D9407DB94004DF5861A2AAAF0F8CB65AD07D329
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
